### ISSUE TITLE
Factions

### ISSUE THREAD

**Issue by ackxs** [SoRadGaming/UESL-World#2]
Phantoms are a big problem due to not being able to sleep if everyone is not sleeping
Boats count as a "ground item" even when rowing so they get removed when ground items get removed
Faction land is too small when claimed

**Comment by SoRadGaming** [comment]
The boat issue should be fixed now, the other two issues are being fixed

**Comment by SoRadGaming** [comment]
Phantoms issue should be fixed in day one patch

**Comment by ackxs** [comment]
😀

**Comment by SoRadGaming** [comment]
What do you mean by factions land is too small, its currently 1 chunk at a time, could you elaborate please

> Phantoms are a big problem due to not being able to sleep if everyone is not sleeping
> Boats count as a "ground item" even when rowing so they get removed when ground items get removed
> Faction land is too small when claimed

**Comment by SoRadGaming** [comment]
All issues resolved, factions had a bug with chunks, all good now
